pre-commit:
  jobs:
    - name: dotnet Format
      glob:
        - "*.cs"
        - "*.csproj"
        - "*.sln"
        - "*.slnx"
        - ".editorconfig"
        - "global.json"
        - "packages.lock.json"
      run: dotnet format --verify-no-changes

    - name: dotnet Test
      glob:
        - "*.cs"
        - "*.csproj"
        - "*.sln"
        - "*.slnx"
        - ".editorconfig"
        - "global.json"
        - "packages.lock.json"
      run: dotnet test

    - name: Actions Lint
      glob: ".github/workflows/*.yml"
      run: actionlint
